#!/usr/bin/env bash
# Write .env for this machine, create data directories, and build the chat image.
# Fill proton.env with a WireGuard key before the first `docker compose up`.
set -euo pipefail

ROOT="${FARNSWORTH_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
ENV_FILE="$ROOT/.env"
PROTON_EXAMPLE="$ROOT/proton.env.example"
PROTON_FILE="$ROOT/proton.env"
GLUETUN_EXAMPLE="$ROOT/helpers/gluetun-auth.toml.example"

usage() {
  cat <<'EOF'
Usage: scripts/install.sh [--non-interactive] [--up]

Asks for the media disk, config directory, and LAN address, then writes .env.
Existing .env is left alone. Pass --up to build the chat image and start the
stack after the WireGuard key is present.

  --non-interactive   Read MEDIA_ROOT, CONFIG_ROOT, and LAN_IP from the environment
  --up                docker compose build && docker compose up -d
EOF
}

die() {
  echo "install: $*" >&2
  exit 1
}

secret() {
  python3 -c 'import secrets; print(secrets.token_urlsafe(18))'
}

cidr_from_ip() {
  local ip="$1"
  local a b c
  IFS=. read -r a b c _ <<<"$ip"
  printf '%s.%s.%s.0/24' "$a" "$b" "$c"
}

detect_ip() {
  ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit }}'
}

detect_tz() {
  if [[ -e /etc/localtime ]]; then
    timedatectl show -p Timezone --value 2>/dev/null || true
  fi
}

firewall_subnets() {
  local lan="$1" extra="$2"
  if [[ -n "$extra" ]]; then
    printf '%s,%s,172.16.0.0/12' "$lan" "$extra"
  else
    printf '%s,172.16.0.0/12' "$lan"
  fi
}

ask() {
  local prompt="$1" default="$2" reply
  read -r -p "$prompt [$default]: " reply
  printf '%s' "${reply:-$default}"
}

write_env() {
  local chat_pass grafana_pass sonarr_pass radarr_pass gluetun_pass
  chat_pass="$(secret)"
  grafana_pass="$(secret)"
  sonarr_pass="$(secret)"
  radarr_pass="$(secret)"
  gluetun_pass="$(secret)"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/install.sh. Do not commit.
PUID=${PUID}
PGID=${PGID}
TZ=${TZ}
VERSION=docker
PLEX_CONFIG=${PLEX_CONFIG}
REMOTE=${REMOTE}
REMOTE_DIR=${REMOTE_DIR}

MEDIA_ROOT=${MEDIA_ROOT}
CONFIG_ROOT=${CONFIG_ROOT}
HOST_ROOT_PATH=${HOST_ROOT_PATH}
VPN_COUNTRY=${VPN_COUNTRY}
CHAT_IMAGE=${CHAT_IMAGE}

QBIT_PUID=${QBIT_PUID}
QBIT_PGID=${QBIT_PGID}
QBIT_WEBUI_PORT=8080
QBIT_TORRENTING_PORT=6881
QBIT_CONFIG=${CONFIG_ROOT}/qbittorrent/config
QBIT_DOWNLOADS=${MEDIA_ROOT}/Downloads
GLUETUN_CONFIG=${CONFIG_ROOT}/gluetun

LAN_IP=${LAN_IP}
LAN_CIDR=${LAN_CIDR}
EXTRA_CIDRS=${EXTRA_CIDRS}
FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
PLEX_URL=http://${LAN_IP}:32400

PLEX_TOKEN=change-me
QBIT_USER=
QBIT_PASS=
PLEX_QBIT_THROTTLE_ON=wan
PLEX_QBIT_DATA=${CONFIG_ROOT}/plex-qbit
QBIT_ORGANIZE_DATA=${CONFIG_ROOT}/qbit-organize
IMDB_DAILY_DATA=${CONFIG_ROOT}/imdb-daily
OLLAMA_DATA=${CONFIG_ROOT}/ollama
OLLAMA_MODEL=${OLLAMA_MODEL}
PLEX_CHAT_PORT=7680
PLEX_CHAT_USER=${PLEX_CHAT_USER}
PLEX_CHAT_PASSWORD=${chat_pass}
MAX_TORRENT_GIB=20

SONARR_CONFIG=${CONFIG_ROOT}/sonarr/config
RADARR_CONFIG=${CONFIG_ROOT}/radarr/config
BAZARR_CONFIG=${CONFIG_ROOT}/bazarr/config
SONARR_AUTH_USER=${SONARR_AUTH_USER}
SONARR_AUTH_PASSWORD=${sonarr_pass}
RADARR_AUTH_USER=${RADARR_AUTH_USER}
RADARR_AUTH_PASSWORD=${radarr_pass}

NTFY_DATA=${CONFIG_ROOT}/ntfy
GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
GRAFANA_ADMIN_PASSWORD=${grafana_pass}
GRAFANA_DATA=${CONFIG_ROOT}/grafana
VM_DATA=${CONFIG_ROOT}/victoriametrics
VL_DATA=${CONFIG_ROOT}/victorialogs
ALLOY_DATA=${CONFIG_ROOT}/alloy
GLUETUN_CONTROL_USER=control
GLUETUN_CONTROL_PASSWORD=${gluetun_pass}
EOF
  chmod 600 "$ENV_FILE"
  printf '%s\n' "$gluetun_pass"
}

install_gluetun_auth() {
  local password="$1" dest="$CONFIG_ROOT/gluetun/auth/config.toml"
  mkdir -p "$(dirname "$dest")"
  if [[ -f "$dest" ]]; then
    echo "gluetun auth already exists: $dest"
    return
  fi
  sed "s/password = \"change-me\"/password = \"${password//\//\\/}\"/" "$GLUETUN_EXAMPLE" >"$dest"
  chmod 600 "$dest"
}

make_dirs() {
  mkdir -p \
    "$MEDIA_ROOT/TV" \
    "$MEDIA_ROOT/Movies" \
    "$MEDIA_ROOT/Downloads" \
    "$CONFIG_ROOT/qbittorrent/config" \
    "$CONFIG_ROOT/gluetun/auth" \
    "$CONFIG_ROOT/plex-qbit" \
    "$CONFIG_ROOT/qbit-organize" \
    "$CONFIG_ROOT/imdb-daily" \
    "$CONFIG_ROOT/ollama" \
    "$CONFIG_ROOT/sonarr/config" \
    "$CONFIG_ROOT/radarr/config" \
    "$CONFIG_ROOT/bazarr/config" \
    "$CONFIG_ROOT/ntfy" \
    "$CONFIG_ROOT/grafana" \
    "$CONFIG_ROOT/victoriametrics" \
    "$CONFIG_ROOT/victorialogs" \
    "$CONFIG_ROOT/alloy"
  if [[ ! -d "$PLEX_CONFIG" ]]; then
    mkdir -p "$PLEX_CONFIG" 2>/dev/null || echo "Could not create $PLEX_CONFIG. Create it as root before starting Plex."
  fi
}

collect_interactive() {
  local detected_ip detected_tz
  detected_ip="$(detect_ip || true)"
  detected_tz="$(detect_tz || true)"
  MEDIA_ROOT="$(ask "Media root (TV, Movies, and Downloads are created under it)" "/srv/media")"
  CONFIG_ROOT="$(ask "Config root" "/srv/farnsworth")"
  LAN_IP="$(ask "LAN address for admin UIs" "${detected_ip:-192.0.2.10}")"
  LAN_CIDR="$(ask "LAN subnet" "$(cidr_from_ip "$LAN_IP")")"
  EXTRA_CIDRS="$(ask "Extra subnet that may reach the host (empty to skip)" "")"
  TZ="$(ask "Timezone" "${detected_tz:-UTC}")"
  PUID="$(ask "Plex user id" "$(id -u)")"
  PGID="$(ask "Plex group id" "$(id -g)")"
  QBIT_PUID="$(ask "Download user id" "$(id -u)")"
  QBIT_PGID="$(ask "Download group id" "$(id -g)")"
  VPN_COUNTRY="$(ask "VPN server country" "Switzerland")"
  PLEX_CONFIG="$(ask "Plex config directory" "/var/lib/plexmediaserver")"
  OLLAMA_MODEL="$(ask "Ollama model" "qwen2.5:1.5b")"
  PLEX_CHAT_USER="$(ask "Chat username" "$(id -un)")"
  SONARR_AUTH_USER="$(ask "Sonarr username" "$(id -un)")"
  RADARR_AUTH_USER="$(ask "Radarr username" "$(id -un)")"
  GRAFANA_ADMIN_USER="$(ask "Grafana username" "admin")"
  HOST_ROOT_PATH="$(ask "Host path mounted read-only for disk stats" "/")"
  REMOTE="$(ask "SSH target for scripts/push-to-puck.sh" "$(id -un)@$(hostname -s)")"
  REMOTE_DIR="$(ask "Remote checkout path" "$CONFIG_ROOT/puck-plex")"
}

collect_noninteractive() {
  MEDIA_ROOT="${MEDIA_ROOT:?MEDIA_ROOT is required}"
  CONFIG_ROOT="${CONFIG_ROOT:?CONFIG_ROOT is required}"
  LAN_IP="${LAN_IP:?LAN_IP is required}"
  LAN_CIDR="${LAN_CIDR:-$(cidr_from_ip "$LAN_IP")}"
  EXTRA_CIDRS="${EXTRA_CIDRS:-}"
  TZ="${TZ:-$(detect_tz || true)}"
  TZ="${TZ:-UTC}"
  PUID="${PUID:-$(id -u)}"
  PGID="${PGID:-$(id -g)}"
  QBIT_PUID="${QBIT_PUID:-$(id -u)}"
  QBIT_PGID="${QBIT_PGID:-$(id -g)}"
  VPN_COUNTRY="${VPN_COUNTRY:-Switzerland}"
  PLEX_CONFIG="${PLEX_CONFIG:-/var/lib/plexmediaserver}"
  OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:1.5b}"
  PLEX_CHAT_USER="${PLEX_CHAT_USER:-$(id -un)}"
  SONARR_AUTH_USER="${SONARR_AUTH_USER:-$(id -un)}"
  RADARR_AUTH_USER="${RADARR_AUTH_USER:-$(id -un)}"
  GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
  HOST_ROOT_PATH="${HOST_ROOT_PATH:-/}"
  REMOTE="${REMOTE:-$(id -un)@$(hostname -s)}"
  REMOTE_DIR="${REMOTE_DIR:-$CONFIG_ROOT/puck-plex}"
}

main() {
  local noninteractive=0 do_up=0 gluetun_pass
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --non-interactive) noninteractive=1 ;;
      --up) do_up=1 ;;
      -h|--help) usage; exit 0 ;;
      *) die "unknown argument: $1" ;;
    esac
    shift
  done

  if [[ -e "$ENV_FILE" ]]; then
    die "$ENV_FILE already exists. Edit it, or move it aside to generate a new one."
  fi
  [[ -f "$PROTON_EXAMPLE" && -f "$GLUETUN_EXAMPLE" ]] || die "missing example files in $ROOT"

  CHAT_IMAGE="${CHAT_IMAGE:-puck-plex-chat:local}"
  if [[ "$noninteractive" -eq 1 ]]; then
    collect_noninteractive
  else
    [[ -t 0 ]] || die "no terminal. Pass --non-interactive and set MEDIA_ROOT, CONFIG_ROOT, and LAN_IP."
    collect_interactive
  fi
  FIREWALL_OUTBOUND_SUBNETS="$(firewall_subnets "$LAN_CIDR" "$EXTRA_CIDRS")"

  gluetun_pass="$(write_env)"
  if [[ ! -f "$PROTON_FILE" ]]; then
    cp "$PROTON_EXAMPLE" "$PROTON_FILE"
    chmod 600 "$PROTON_FILE"
  fi
  install_gluetun_auth "$gluetun_pass"
  make_dirs

  cat <<EOF

Wrote $ENV_FILE
Media:  $MEDIA_ROOT
Config: $CONFIG_ROOT
LAN:    http://$LAN_IP:7680  (chat)  http://$LAN_IP:32400  (Plex)
Passwords are in .env. Chat user is $PLEX_CHAT_USER.

Next: paste a WireGuard private key into $PROTON_FILE
Then: docker compose -f $ROOT/docker-compose.yml --project-directory $ROOT up -d
EOF

  if [[ "$do_up" -eq 1 ]]; then
    if ! grep -q '^WIREGUARD_PRIVATE_KEY=.\+' "$PROTON_FILE"; then
      die "WIREGUARD_PRIVATE_KEY is empty in $PROTON_FILE"
    fi
    docker compose -f "$ROOT/docker-compose.yml" --project-directory "$ROOT" build plex-chat
    docker compose -f "$ROOT/docker-compose.yml" --project-directory "$ROOT" up -d
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
